### ISSUE TITLE
All telemetry slots full

### ISSUE THREAD

**Issue by dk7xe** [Clooney82/MavLink_FrSkySPort#10]
i have read the conversation on this topic on the diydrones forum and based on the explanation given this is caused by duplicate sensor stuff.

I started with a clean model and entered all the sensors manually (model file available on https://drive.google.com/folderview?id=0BxM1Ej9W_KZ7flI0cFJsaGZwTDVId2stSkxQT29OTmhpUF9pc0FleUxkUGl2UWRqQzV5NkE&usp=sharing ) according the pictures provided by Clooney. My understanding is that the error should not come up in this case, right?

But it does. Environment used is EeePC1201N / Opensuse13.2_64 / companion 2.1.1

Since i don't have my Teensy3.1 programmed yet i purely do the tests with companion simulator.
Error message appears when i start simulating parameters and enter something (other than RSSI, SWR or A1).
![screenshot - 09052015 - 11 22 27 pm](https://cloud.githubusercontent.com/assets/3907200/9701398/f2ad6872-5426-11e5-9bac-db58c34f7b5d.png)
![screenshot - 09052015 - 11 25 06 pm](https://cloud.githubusercontent.com/assets/3907200/9701399/f2af1ffa-5426-11e5-8e1c-f46fc3d557a4.png)

**Comment by Clooney82** [comment]
I think this could be a problem of openTX simulator.
Didn´t test Telemetry Simulator till now.

**Comment by Clooney82** [comment]
Fixed with openTX 2.1.2:

> Telemetry sensors are no longer continuously detected, it is now necessary to go to the telemetry setup page and manually select the “Discover new sensors” menu item. This prevents creation of non-existing sensors in case of transmission errors, and allows excluding sensors that are received but considered uninteresting.
