### ISSUE TITLE
Create wiki

### ISSUE THREAD

**Issue by Clooney82** [Clooney82/MavLink_FrSkySPort#11]
Wouldn´t it be great to have a wiki for this project?

**Comment by dk7xe** [comment]
Indeed, i was thinking about the same while driving home tonight. Because i was struggling with which telemetry value is representing what. I know it's in the code but i would like to start with creating an overview on that. If you like i can take over this part. (telemetry values and their meaning)

**Comment by Clooney82** [comment]
Feel free to contribute ;)

**Comment by Clooney82** [comment]
I added first wiki entries.

**Comment by Clooney82** [comment]
Please update wiki for current development.
Describe your LUA Script, and how to configure them.
Also if something change on teensy side.

**Comment by dk7xe** [comment]
i have updated the [1.2.1 Telemetry Value Overview ](https://github.com/Clooney82/MavLink_FrSkySPort/wiki/1.2.1-Telemetry-Value-Overview) page with the information based on what i have found on 1.2. FrSky Taranis Telemetry.
The values Cels, GPS, GSpd and SWR needs a review still

Please let me know if this is sufficient and feel free to update ;-)

Gerald

**Comment by Clooney82** [comment]
Looks good so far.
Now we must keep everything up-to-date.
Maybe we need to add more detailed instructions to setup everything.

**Comment by athertop** [comment]
I would be happy to get involved in updating the Wiki. I can certainly add info on the different lua script versions now if that is OK with you guys?

**Comment by Clooney82** [comment]
Feel free to make modifications ;) and welcome on bord.

**Comment by athertop** [comment]
@Clooney82 - I have done quite a bit of work on the Wiki - on my own fork initially before copying it over here. I'm not quite finished with it yet, but before I copy it, I would really appreciate if you have the time, to check out the new Wiki content - kind of proof read it from a technical perspective if you will?

(you will have noticed that I added extra images to the images folder on this (Clooney82) repository. I put them here purposely - as I have used these in my updated pages, and wanted to make sure that when I migrate the wiki over here, that all the references carry over OK)

My wiki/fork is here: https://github.com/athertop/MavLink_FrSkySPort/wiki

I have re-written/amended all the pages up to (but not including) 2.1.2 - I still have the final few pages to work on. I won't be touching the LED page at all, as I have little knowledge of this area.

**Comment by Clooney82** [comment]
@athertop - looks good. for my good to understand. think now some parts become more clear.

**Comment by athertop** [comment]
I still have a fair bit of work to do on it, so will let you know when 
I'm near completion. Thanks for checking it.

**Comment by athertop** [comment]
OK, I have merged my changes into the Wiki. Please feel free to check and comment. Thanks, Paul
