### ISSUE TITLE
removing HEX files ?

### ISSUE THREAD

**Issue by Clooney82** [Clooney82/MavLink_FrSkySPort#14]
Is it possible to remove pre compiled HEX files, or should someone update them?

**Comment by wolkstein** [comment]
yes.. removing removing:) they are outdated. i think if development on teensy hardware side reach an stable state we can create new hex files.
/g
wolke

**Comment by Clooney82** [comment]
removed with commit: https://github.com/Clooney82/MavLink_FrSkySPort/commit/289212e1dcd718a92efb5b837151b8af91558e17
