### ISSUE TITLE
lua telem1.lua Radar do not work

### ISSUE THREAD

**Issue by wolkstein** [Clooney82/MavLink_FrSkySPort#22]
the radar on telem1.lua do not work correctly. heading is displayed but no movements on screen. also distance to home is zero.

/g
wolke

**Comment by wolkstein** [comment]
fixed in commit 56e56d33d5f0aabcea9d29e0e3ea2f520982219e .
this fix need opentx2.1.3.

**Comment by fnoop** [comment]
Great fix, thanks!
