### ISSUE TITLE
remove unused images and sound file

### ISSUE THREAD

**Issue by Clooney82** [Clooney82/MavLink_FrSkySPort#26]
We hava a lot of images and sound files provided. 
Not all are used, maybe we can sort out images and sound file which are not used.

And also, we could regenerate sound files completely, to have a consistent voice.

**Comment by wolkstein** [comment]
the sound files i generate was created with http://www.oddcast.com/home/demos/tts/tts_example.php .
for some reasons i create different sounds to ensure that some messages simple get more ore other attention. most files are created by lvale. i think he also have in mind, that he use for some messages also different voices. also as filter for listeners.

/g
wolke

at this point we have to talk with lvale because licence things. it is important that all files, images beside snd files need an proper licence.
imo we can choose the right license here.
 http://creativecommons.org/choose/ 

second edit:
it is real hard work to generate the sound files and save them in the right snd-file format.i am thinking to creat an small sox script which help to convert them right.

see sndfile-info

``` bash
 sndfile-info develop/git/MavLink_FrSkySPort_Coloboration_Cloony82/Lua_Telemetry/DisplayApmPosition/SOUNDS/en/ServMain.wav 

Version : libsndfile-1.0.25

========================================
File : develop/git/MavLink_FrSkySPort_Coloboration_Cloony82/Lua_Telemetry/DisplayApmPosition/SOUNDS/en/ServMain.wav
Length : 198652
RIFF : 198644
WAVE
fmt  : 16
  Format        : 0x1 => WAVE_FORMAT_PCM
  Channels      : 1
  Sample Rate   : 32000
  Block Align   : 2
  Bit Width     : 16
  Bytes/sec     : 64000
data : 198482
LIST : 44
  INFO
    IART : Michael Wolkstein
    ICRD : 2015
*** id3  : 66 (unknown marker)
End

----------------------------------------
Sample Rate : 32000
Frames      : 99241
Channels    : 1
Format      : 0x00010002
Sections    : 1
Seekable    : TRUE
Duration    : 00:00:03.101
Signal Max  : 31762 (-0.27 dB)

```

**Comment by fnoop** [comment]
Funny, I had already started work on this in the background.  I'm creating an automated way of pulling messages and generating soundfiles, using a variety of speech synthesisors and voices.

**Comment by wolkstein** [comment]
the open-source text to speech synthesizer i know and also i am using some times, is festival. it is really easy to use in console. also it is easy to write simple scripts. but the results are imo not so nice than the results from online text to speech synths.

which synths did you use?

**Comment by fnoop** [comment]
Basically wrappers around the google tts, like:
 https://github.com/desbma/GoogleSpeech
The quality is the best that I found so far.

**Comment by wolkstein** [comment]
cool, desbma is licensed under GPLv3. need at least some good sound fonts. do you know if snd files generated with google tts are free to distribute?

**Comment by lvale** [comment]
There is a new good option now.
https://play.google.com/store/apps/details?id=com.adrionics.android.opentx.speech

although I still prefer using MacOSX TTS voices.

**Comment by Clooney82** [comment]
I create soundfiles  with OS Tools, like here described: http://openrcforums.com/forum/viewtopic.php?f=64&t=6871

This is very easy for me, and generates files in background. Only Input as csv file is needed.

**Comment by fnoop** [comment]
A further problem with messages now is that copter-3.3 doesn't just have fixed text strings, it has variable prearm messages generated by EKF.  I think we probably need to keep a lookup table of static messages as before, but also have a separate EKF/Vibe function as per the new GCS functionalities.

**Comment by Clooney82** [comment]
For Soundfile generation I need a csv file in the following format:

| Path | Filename | Language (EN) | Language (DE) | Language XY |
| --- | --- | --- | --- | --- |
| /system | 0000 | 0 | 0 | 0 |
| /system | rssi_org | RSSI low | RSSI niedrig | ... |

For a complete sound pack I need about 5-10min per Language, but my own translation is currently not complete.

**Comment by Clooney82** [comment]
Just pushed my soundgen to github: https://github.com/Clooney82/MavLink_FrSkySPort/commit/1eb574cb115413e48e3936ff193bda14a4d3f603

**Comment by lvale** [comment]
Good job. I believe that for "normal" users a prebuilt sound pack in English EN-US would be better with all the sounds using the same voice. I tend to use AVA as the voice for all system sounds and also for all the messages.

**Comment by Clooney82** [comment]
think for new sound we should use a seperated folder, like 
/SOUNDS/_language_/**TELEM**/
or
/SOUNDS/_language_/**mavlink**/
