### ISSUE TITLE
Report FAKE FLVSS Values like in old Version

### ISSUE THREAD

**Issue by Clooney82** [Clooney82/MavLink_FrSkySPort#30]
Hi,
I got [informed](http://www.kopterforum.de/topic/37360-apm-mavlink-to-frsky-x8r-sport-converter/?p=593136) from a user who wishes old behavior of transmitting a fake flvss sensor even if no LSCM is used.

See: https://github.com/Clooney82/MavLink_FrSkySPort/blob/s-c-l-v-rc/MavLink_FrSkySPort/FrSkySPort.ino 
Lines 85-172

What do use think about this?

**Comment by wolkstein** [comment]
a must have. it is more easy to monitor the voltage of one cell. because you do not must calculate limits for different lipos.
/g
wolke

**Comment by Clooney82** [comment]
Implemented with commit https://github.com/Clooney82/MavLink_FrSkySPort/commit/9e45997a807b15479d1b0c8b04d07ba3324191dc
