### ISSUE TITLE
GPS fix handling with AC3.3

### ISSUE THREAD

**Issue by Clooney82** [Clooney82/MavLink_FrSkySPort#38]
A Little bug from diydrones:

The Teensy sends GPS Data only, if the APM signals a 3D fix to avoid the use of bad coordinates.

The newer APM Firmware (I'm using the latest AC 3.3 Beta) expands the GPS Status to 4=DGPS, 5= RTK.

All discussed implementations here include at least 2 conditional  statements in their Arduino sketches for

GPS Status testing:

```
          if(ap_fixtype==3)
```

So, if you're using a modern GPS chip and get a DGPS fix, ap_fixtype will become 4 and the GPS data on your Taranis stucks...

The Solution is simple, please change all occurences of "if(ap_fixtype==3)" to "if(ap_fixtype>=3)" and your Taranis

**Comment by lvale** [comment]
That is a GPS status: 4=DGPS, 3=3D, 2=2D, <1=NOFIX

although I prefer to use

4=DGPS, 3=3D, <2=NOFIX
