### ISSUE TITLE
Duplicate FastLED library warning/notification

### ISSUE THREAD

**Issue by fnoop** [Clooney82/MavLink_FrSkySPort#4]
In file included from led_control.ino:18:0:
Arduino/libraries/FastLED/FastLED.h:12:2: warning: #warning FastLED version 3001000 (Not really a warning, just telling you here.) [-Wcpp]
# warning FastLED version 3001000  (Not really a warning, just telling you here.)

**Comment by Clooney82** [comment]
No error, only warning.
Comes from FastLED Library.

**Comment by fnoop** [comment]
I guess because it overrides the FastLED library included with the arduino/teensy install.  Is the updated library necessary?
Not important I guess, I'm just a bit anal retentive about warnings, I like cleanliness :)

**Comment by Clooney82** [comment]
I prefer to include all used libraries, which are not included automatically in arduino IDE.

**Comment by Clooney82** [comment]
should now be solved with final FastLED 3.1 Library from commit: https://github.com/Clooney82/MavLink_FrSkySPort/commit/c9544299f9bd39ea5d277af98026ecea7627b5ab
