### ISSUE TITLE
Provide .zip GCS_MAVLink library

### ISSUE THREAD

**Issue by fnoop** [Clooney82/MavLink_FrSkySPort#5]
FrSkySportTelemetry.zip and FastLED.zip are in zip form but GCS_MAVLink is in directory form.  Should be zip form with instructions in readme for installation.

**Comment by Clooney82** [comment]
Should be no problem to provide Library as a zip file.

**Comment by Clooney82** [comment]
fixed with commit: https://github.com/Clooney82/MavLink_FrSkySPort/commit/be65a0f1947379119df54182a025b6f6d19fbedc
For installing library see: https://www.arduino.cc/en/pmwiki.php?n=Guide/Libraries#toc4

**Comment by fnoop** [comment]
For consistency, we should remove GCS_MAVLink directory?

**Comment by fnoop** [comment]
Confirmed current GCS_MAVLink directory is exactly the same as the zip file:

> diff GCS_MAVLink tmp/GCS_MAVLink
> Common subdirectories: GCS_MAVLink/include and tmp/GCS_MAVLink/include
> Common subdirectories: GCS_MAVLink/message_definitions and tmp/GCS_MAVLink/message_definitions

**Comment by fnoop** [comment]
Removed directory:
 https://github.com/Clooney82/MavLink_FrSkySPort/commit/c9d47b196897d24a0288f10131dd84a9592d5b05
