### ISSUE TITLE
telem1.lua - Not enough memory

### ISSUE THREAD

**Issue by JyriT** [Clooney82/MavLink_FrSkySPort#67]
While using telem1.lua as secondary telemetry screen on Taranis plus. 
It prints on screen Script syntax error not enough memory.
Changing back to coptr217.lua works ok.

**Comment by athertop** [comment]
Yes, that is the old telemetry screen which did not receive any of the updates to make it work with the scaling changes in OpenTx  2.1.7. I think I should probably drop it from the project and update the wiki to say that the project is only supported with 2.1.7  or newer.

**Comment by athertop** [comment]
Support for older versions of OTx 2.1 has been dropped. Closing.
