### ISSUE TITLE
Code should default to not using single cell monitor or fastled

### ISSUE THREAD

**Issue by fnoop** [Clooney82/MavLink_FrSkySPort#7]
Optional hardware support should be turned off by default, vast majority of users won't use this

**Comment by Clooney82** [comment]
You're right. 
Haven't tested without single cell monitor.

**Comment by Clooney82** [comment]
Now all AddOns are disabled by default: https://github.com/Clooney82/MavLink_FrSkySPort/commit/3be689b10ac460627b9e35671156d4e971a4d682
